language: java
sudo: true
install: true
jdk:
  - oraclejdk8
before_install: cd bot-moe
script:
  - ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=tdd -Dsonar.login=96fd56d655c0572f286d89397bae31a605419672
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
